class IPL
 {
 public static void main(String team[])
 {
 String rcbPlayers[]={"Virat","ABD","Maxwell","DK","siraj","faf","pattidar","ahmed","hasaranga","Villi","patel"};
 System.out.println("rcbPlayers are:");
 System.out.println(rcbPlayers[0]);
 System.out.println(rcbPlayers[1]);
 System.out.println(rcbPlayers[2]);
 System.out.println(rcbPlayers[3]);
 System.out.println(rcbPlayers[4]);
 System.out.println(rcbPlayers[5]);
 System.out.println(rcbPlayers[6]);
System.out.println(rcbPlayers[7]);
System.out.println(rcbPlayers[8]);
System.out.println(rcbPlayers[9]);
System.out.println(rcbPlayers[10]);
String cskPlayers[]={"MSD","devon","rutu","subhranshu","ambati","ajinkya","shaik","jadeja","dwaine","mitchell","ali"};
 System.out.println("cskPlayers are:");
 System.out.println(cskPlayers[0]);
 System.out.println(cskPlayers[1]);
 System.out.println(cskPlayers[2]);
 System.out.println(cskPlayers[3]);
 System.out.println(cskPlayers[4]);
 System.out.println(cskPlayers[5]);
 System.out.println(cskPlayers[6]);
System.out.println(cskPlayers[7]);
System.out.println(cskPlayers[8]);
System.out.println(cskPlayers[9]);
System.out.println(cskPlayers[10]);
String gtPlayers[]={"pandya","gill","kane","rashid","david","joseph","darshan","jayanth","pradeep","wade","abhinav"};
 System.out.println("gtplayers are:");
 System.out.println(gtPlayers[0]);
 System.out.println(gtPlayers[1]);
 System.out.println(gtPlayers[2]);
 System.out.println(gtPlayers[3]);
 System.out.println(gtPlayers[4]);
 System.out.println(gtPlayers[5]);
 System.out.println(gtPlayers[6]);
System.out.println(gtPlayers[7]);
System.out.println(gtPlayers[8]);
System.out.println(gtPlayers[9]);
System.out.println(gtPlayers[10]);
String lsgPlayers[]={"Klrahul","kyle","mark","ayush","pooraan","krunal","avesh","thakur","deepak","singh","kock"};
 System.out.println("lsgPlayers are:");
 System.out.println(lsgPlayers[0]);
 System.out.println(lsgPlayers[1]);
 System.out.println(lsgPlayers[2]);
 System.out.println(lsgPlayers[3]);
 System.out.println(lsgPlayers[4]);
 System.out.println(lsgPlayers[5]);
 System.out.println(lsgPlayers[6]);
System.out.println(lsgPlayers[7]);
System.out.println(lsgPlayers[8]);
System.out.println(lsgPlayers[9]);
System.out.println(lsgPlayers[10]);
String kkrPlayers[]={"iyer","rinku","shardul","garbar","russel","rana","venkatesh","varun","umesh","vibhav","roy"};
 System.out.println(" kkrPlayers are:");
 System.out.println(kkrPlayers[0]);
 System.out.println(kkrPlayers[1]);
 System.out.println(kkrPlayers[2]);
 System.out.println(kkrPlayers[3]);
 System.out.println(kkrPlayers[4]);
 System.out.println(kkrPlayers[5]);
 System.out.println(kkrPlayers[6]);
System.out.println(kkrPlayers[7]);
System.out.println(kkrPlayers[8]);
System.out.println(kkrPlayers[9]);
System.out.println(kkrPlayers[10]);
String rrPlayers[]={"sanju","jos","devdatt","root","riyan","ashwin","krishna","holder","sharma","hetmyer","jaiswal"};
 System.out.println(" rrPlayers are:");
 System.out.println(rrPlayers[0]);
 System.out.println(rrPlayers[1]);
 System.out.println(rrPlayers[2]);
 System.out.println(rrPlayers[3]);
 System.out.println(rrPlayers[4]);
 System.out.println(rrPlayers[5]);
 System.out.println(rrPlayers[6]);
System.out.println(rrPlayers[7]);
System.out.println(rrPlayers[8]);
System.out.println(rrPlayers[9]);
System.out.println(rrPlayers[10]);
String srhPlayers[]={"umran","brook","agarwal","bhvaneshwar","rahul","singh","natarajan","nitish","yadav","sharma","upendra"};
 System.out.println(" srhPlayers are:");
 System.out.println(srhPlayers[0]);
 System.out.println(srhPlayers[1]);
 System.out.println(srhPlayers[2]);
 System.out.println(srhPlayers[3]);
 System.out.println(srhPlayers[4]);
 System.out.println(srhPlayers[5]);
 System.out.println(srhPlayers[6]);
System.out.println(srhPlayers[7]);
System.out.println(srhPlayers[8]);
System.out.println(srhPlayers[9]);
System.out.println(srhPlayers[10]);
String pkPlayers[]={"dhawan","jonny","matt","sam curran","kagiso","jitesh","nathan","shivam","raj bawa","baltej","mohit"};
 System.out.println(" pkPlayers are:");
 System.out.println(pkPlayers[0]);
 System.out.println(pkPlayers[1]);
 System.out.println(pkPlayers[2]);
 System.out.println(pkPlayers[3]);
 System.out.println(pkPlayers[4]);
 System.out.println(pkPlayers[5]);
 System.out.println(pkPlayers[6]);
System.out.println(pkPlayers[7]);
System.out.println(pkPlayers[8]);
System.out.println(pkPlayers[9]);
System.out.println(pkPlayers[10]);
String miPlayers[]={"rohith sharma","suryakumar","cameron","jofra","tim david","oiyush","bumrah","arjun","ishan","hrithik","vishnu"};
 System.out.println(" miPlayers are:");
 System.out.println(miPlayers[0]);
 System.out.println(miPlayers[1]);
 System.out.println(miPlayers[2]);
 System.out.println(miPlayers[3]);
 System.out.println(miPlayers[4]);
 System.out.println(miPlayers[5]);
 System.out.println(miPlayers[6]);
System.out.println(miPlayers[7]);
System.out.println(miPlayers[8]);
System.out.println(miPlayers[9]);
System.out.println(miPlayers[10]);
String dcPlayers[]={"axar  patel","lalit  yadav","marsh","david  warner","ripal patel","vicky","aman khan","prithvi","chetan","yash dhull","lungi ngidi"};
 System.out.println(" dcPlayers are:");
 System.out.println(dcPlayers[0]);
 System.out.println(dcPlayers[1]);
 System.out.println(dcPlayers[2]);
 System.out.println(dcPlayers[3]);
 System.out.println(dcPlayers[4]);
 System.out.println(dcPlayers[5]);
 System.out.println(dcPlayers[6]);
System.out.println(dcPlayers[7]);
System.out.println(dcPlayers[8]);
System.out.println(dcPlayers[9]);
System.out.println(dcPlayers[10]);
 }
 }
 